// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: kademlia.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// KademliaProtocolClient is the client API for KademliaProtocol service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KademliaProtocolClient interface {
	Ping(ctx context.Context, in *Bucket, opts ...grpc.CallOption) (*Bucket, error)
	Store(ctx context.Context, opts ...grpc.CallOption) (KademliaProtocol_StoreClient, error)
	FindNode(ctx context.Context, in *TargetID, opts ...grpc.CallOption) (*KBucket, error)
	FindValue(ctx context.Context, in *TargetID, opts ...grpc.CallOption) (KademliaProtocol_FindValueClient, error)
}

type kademliaProtocolClient struct {
	cc grpc.ClientConnInterface
}

func NewKademliaProtocolClient(cc grpc.ClientConnInterface) KademliaProtocolClient {
	return &kademliaProtocolClient{cc}
}

func (c *kademliaProtocolClient) Ping(ctx context.Context, in *Bucket, opts ...grpc.CallOption) (*Bucket, error) {
	out := new(Bucket)
	err := c.cc.Invoke(ctx, "/kademlia.KademliaProtocol/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kademliaProtocolClient) Store(ctx context.Context, opts ...grpc.CallOption) (KademliaProtocol_StoreClient, error) {
	stream, err := c.cc.NewStream(ctx, &KademliaProtocol_ServiceDesc.Streams[0], "/kademlia.KademliaProtocol/Store", opts...)
	if err != nil {
		return nil, err
	}
	x := &kademliaProtocolStoreClient{stream}
	return x, nil
}

type KademliaProtocol_StoreClient interface {
	Send(*Data) error
	CloseAndRecv() (*Response, error)
	grpc.ClientStream
}

type kademliaProtocolStoreClient struct {
	grpc.ClientStream
}

func (x *kademliaProtocolStoreClient) Send(m *Data) error {
	return x.ClientStream.SendMsg(m)
}

func (x *kademliaProtocolStoreClient) CloseAndRecv() (*Response, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *kademliaProtocolClient) FindNode(ctx context.Context, in *TargetID, opts ...grpc.CallOption) (*KBucket, error) {
	out := new(KBucket)
	err := c.cc.Invoke(ctx, "/kademlia.KademliaProtocol/FindNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kademliaProtocolClient) FindValue(ctx context.Context, in *TargetID, opts ...grpc.CallOption) (KademliaProtocol_FindValueClient, error) {
	stream, err := c.cc.NewStream(ctx, &KademliaProtocol_ServiceDesc.Streams[1], "/kademlia.KademliaProtocol/FindValue", opts...)
	if err != nil {
		return nil, err
	}
	x := &kademliaProtocolFindValueClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type KademliaProtocol_FindValueClient interface {
	Recv() (*FindValueResponse, error)
	grpc.ClientStream
}

type kademliaProtocolFindValueClient struct {
	grpc.ClientStream
}

func (x *kademliaProtocolFindValueClient) Recv() (*FindValueResponse, error) {
	m := new(FindValueResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// KademliaProtocolServer is the server API for KademliaProtocol service.
// All implementations must embed UnimplementedKademliaProtocolServer
// for forward compatibility
type KademliaProtocolServer interface {
	Ping(context.Context, *Bucket) (*Bucket, error)
	Store(KademliaProtocol_StoreServer) error
	FindNode(context.Context, *TargetID) (*KBucket, error)
	FindValue(*TargetID, KademliaProtocol_FindValueServer) error
	mustEmbedUnimplementedKademliaProtocolServer()
}

// UnimplementedKademliaProtocolServer must be embedded to have forward compatible implementations.
type UnimplementedKademliaProtocolServer struct {
}

func (UnimplementedKademliaProtocolServer) Ping(context.Context, *Bucket) (*Bucket, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedKademliaProtocolServer) Store(KademliaProtocol_StoreServer) error {
	return status.Errorf(codes.Unimplemented, "method Store not implemented")
}
func (UnimplementedKademliaProtocolServer) FindNode(context.Context, *TargetID) (*KBucket, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindNode not implemented")
}
func (UnimplementedKademliaProtocolServer) FindValue(*TargetID, KademliaProtocol_FindValueServer) error {
	return status.Errorf(codes.Unimplemented, "method FindValue not implemented")
}
func (UnimplementedKademliaProtocolServer) mustEmbedUnimplementedKademliaProtocolServer() {}

// UnsafeKademliaProtocolServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KademliaProtocolServer will
// result in compilation errors.
type UnsafeKademliaProtocolServer interface {
	mustEmbedUnimplementedKademliaProtocolServer()
}

func RegisterKademliaProtocolServer(s grpc.ServiceRegistrar, srv KademliaProtocolServer) {
	s.RegisterService(&KademliaProtocol_ServiceDesc, srv)
}

func _KademliaProtocol_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Bucket)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KademliaProtocolServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kademlia.KademliaProtocol/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KademliaProtocolServer).Ping(ctx, req.(*Bucket))
	}
	return interceptor(ctx, in, info, handler)
}

func _KademliaProtocol_Store_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(KademliaProtocolServer).Store(&kademliaProtocolStoreServer{stream})
}

type KademliaProtocol_StoreServer interface {
	SendAndClose(*Response) error
	Recv() (*Data, error)
	grpc.ServerStream
}

type kademliaProtocolStoreServer struct {
	grpc.ServerStream
}

func (x *kademliaProtocolStoreServer) SendAndClose(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *kademliaProtocolStoreServer) Recv() (*Data, error) {
	m := new(Data)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _KademliaProtocol_FindNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TargetID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KademliaProtocolServer).FindNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kademlia.KademliaProtocol/FindNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KademliaProtocolServer).FindNode(ctx, req.(*TargetID))
	}
	return interceptor(ctx, in, info, handler)
}

func _KademliaProtocol_FindValue_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TargetID)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KademliaProtocolServer).FindValue(m, &kademliaProtocolFindValueServer{stream})
}

type KademliaProtocol_FindValueServer interface {
	Send(*FindValueResponse) error
	grpc.ServerStream
}

type kademliaProtocolFindValueServer struct {
	grpc.ServerStream
}

func (x *kademliaProtocolFindValueServer) Send(m *FindValueResponse) error {
	return x.ServerStream.SendMsg(m)
}

// KademliaProtocol_ServiceDesc is the grpc.ServiceDesc for KademliaProtocol service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KademliaProtocol_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kademlia.KademliaProtocol",
	HandlerType: (*KademliaProtocolServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _KademliaProtocol_Ping_Handler,
		},
		{
			MethodName: "FindNode",
			Handler:    _KademliaProtocol_FindNode_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Store",
			Handler:       _KademliaProtocol_Store_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "FindValue",
			Handler:       _KademliaProtocol_FindValue_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "kademlia.proto",
}
